int ANSELA = 0;
int ANSELB = 0;
int ANSELC = 0;
int ANSELD = 0;
int PORTC = 0;
int TRISA=0x03; 		
int TRISD=0x00;
int TRISB=0x00;
int PORTD=0x00;
int PORTB=0x00;  
int IPEN = 1;				
int GIEH = 1;				
int GIEL = 1;		
int TRISE;
int CCPTMRS0;
typedef struct type2{
    int CCP3;
    int C3TSEL;
    int RE0;
    int TMR2ON;
    int RC0;
    int RC1;
} type2;
type2 PORTCbits;
type2 TRISEbits;
type2 CCPTMRS0bits;
type2 T2CONbits;
typedef struct T0CONbits  {
int T08BIT;
int T0CS;
int PSA;
int T0SE;
int T0PS;
} type;		
type T0CONbits;
int TMR0IF = 0;				
int TMR0IP = 1;				
int TMR0IE = 1;				
int TMR0H = 'TIMER_STARTH';
int TMR0L = 'TIMER_STARTL';
int TMR0ON = 1;
#define high_priority;
#define low_priority;
int ANSELE;
int TRISC;
int CCP3CON;
int CCPR3L;
int TMR2IF;
int T2CON;
int PR2;